default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  username: db_user
  password: db_password
  host: localhost
  port: 5432

development:
  <<: *default
  database: ats_api_app_development

test:
  <<: *default
  database: ats_api_app_test

production:
  <<: *default
  database: ats_api_app_production
  username: ats_api_app
  password: <%= ENV["ATS_API_APP_DATABASE_PASSWORD"] %>
